## 该服务端口为8762
## 该服务名字是service-hi
## 该服务注册到http://localhost:8761/eureka/注册中心
server:
  port: 8762
spring:
  application:
    name: service-hi
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/